name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
          
      - run: npm install
      
      - name: Build and test extension
        run: xvfb-run -a npm test
        
  publish:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Publish
        if: startsWith( github.ref, 'refs/tags/releases/')
        run: npm run deploy
        env: 
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
